WX_COMPILER_OPTIONS = [
  "-D_UNICODE",
  "-DWIN32",
  "-D_WINDOWS",
  "-DWINVER=0x1000",
  "-D__WXMSW__",
  "-DWXUSINGDLL",
  "-DwxUSE_GUI=1",
  "-D_DEBUG",
  "-D__WXDEBUG__",
  "-D_CRT_SECURE_NO_DEPRECATE",
  "-DCRT_NONSTDC_NO_DEPRECATE",
]